# Generated by Django 4.0.6 on 2022-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='location',
            field=models.IntegerField(max_length=255),
        ),
    ]
