# Generated by Django 4.0.6 on 2022-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelsapp', '0006_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
