# Generated by Django 4.0.6 on 2022-07-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelsapp', '0012_remove_choice_user_uservote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
