# Generated by Django 4.0.6 on 2022-07-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rallyapp', '0003_petition_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='member',
            new_name='created_by',
        ),
    ]
